Calculator c = new Calculator();
//c.welcomeMessage();

integer sum1= Calculator.add(10,15);
system.debug('sum1= '+ sum1);

Calculator.printNewMessage('this is new age calc');

string message='this is new msg for calc class';
Calculator.printNewMessage(message);
//<ineteger> listInteger = new List<integer> ();
//integer listSum = Calculator.add(listInteger);
//System.debug('sum of list element '+listSum);
